language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  
install:
  - sudo apt-get -y install qt510base libgl1-mesa-dev libgit2-dev libssh-dev cmake
  - source /opt/qt*/bin/qt*-env.sh

script:
  # cmark
  - wget -nv https://github.com/commonmark/cmark/archive/0.29.0.tar.gz
  - tar xf 0.29.0.tar.gz
  - cd cmark-*/
  - mkdir build
  - cd build
  - cmake ..  -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make test
  - make install
  - cd ../..
  - git submodule init
  - git submodule update
  - cd dep/openssl/openssl
  - ./config -fPIC
  - make -j$(nproc)
  - cd ..
  # gitahead
  - mkdir -p build/release
  - cd build/release
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh gitahead*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
